repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.9.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [push]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^(src/|tests/)
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        args: [
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        files: ^(src/|tests/)
        args: []
